=== I-am-Gabi/BrowserChronicles/app/stories/story.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="storyType">
        <xs:sequence>
            <xs:element name="init" type="xs:string"/>
            <xs:element name="step" type="stepType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="title" use="required" type="xs:string"/>
    </xs:complexType>
    <xs:element name="story" type="storyType"/>

    <xs:complexType name="stepType">
        <xs:all>
            <xs:element name="title" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="possibility" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="choice" type="choiceType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="nextStep" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="value"  type="xs:IDREF"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="row" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="column" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="hint" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="difficulty" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="theme" type="themeList" minOccurs="0" maxOccurs="1"/>
            <xs:element name="row" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="column" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="win" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="value" use="required" type="xs:boolean"/>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="id" use="required" type="xs:ID"/>
        <xs:attribute name="type" use="required" type="typeStepEnum"/>
    </xs:complexType>
    <xs:simpleType name="typeStepEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="multiChoice"/>
            <xs:enumeration value="riddle"/>
            <xs:enumeration value="end"/>
            <xs:enumeration value="maze"/>
            <xs:enumeration value="memory"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="themeList">
        <xs:restriction base="xs:string">
            <xs:enumeration value="default"/>
            <xs:enumeration value="fruit"/>
            <xs:enumeration value="prof"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="choiceType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="nextStep"  type="xs:IDREF"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== I-am-Gabi/BrowserChronicles/app/stories/Example.xml
<?xml version="1.0"?><story xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="story.xsd" title="Histoire sans fin">
    <init></init>
    <step id="BEGIN" type="multiChoice">
        <title><![CDATA[BEGIN]]></title>
        <description><![CDATA[Welcome to the game example.]]></description>
        <possibility>
            <choice nextStep="s1">Go to the Riddle Step.</choice>
            <choice nextStep="s2">Go to the memory.</choice>
            <choice nextStep="s4">Make me win.</choice>
            <choice nextStep="s5">Make me loose.</choice>
            <choice nextStep="s3">Go to the Rich Text multiChoice.</choice>
        </possibility>
    </step>
    <step id="s1" type="riddle">
        <title><![CDATA[Riddle]]></title>
        <description><![CDATA[I will be yesterday, I was tomorrow.]]></description>
        <hint>It's easy. No hint.</hint>
        <possibility>
            <choice nextStep="s5">Yesterday</choice>
            <choice nextStep="s5">Tomorrow</choice>
            <choice nextStep="BEGIN">Today</choice>
        </possibility>
    </step>
    <step id="s2" type="memory">
        <title><![CDATA[Memory]]></title>
        <description><![CDATA[Look for the pairs]]></description>
        <theme>prof</theme>
        <difficulty>3</difficulty>
        <nextStep value="BEGIN"/>
    </step>
    <step id="s3" type="multiChoice">
        <title><![CDATA[Step with HTML Tag]]></title>
        <description><![CDATA[<b>This</b> step has a <i>html</i> tag and just <b>one</b> option, so choice next.<img class="img-responsive" src="http://science-all.com/images/wallpapers/cute-cat-pictures/cute-cat-pictures-19.jpg" />]]></description>
        <possibility>
            <choice nextStep="BEGIN">Back.</choice>
        </possibility>
    </step>
    <step id="s4" type="end">
        <title><![CDATA[This is the no-fake happy ending!]]></title>
        <description><![CDATA[Congrats!]]></description>
        <win value="true"/>
    </step>
    <step id="s5" type="end">
        <title><![CDATA[This is the happy ending!]]></title>
        <description><![CDATA[I'm sorry.]]></description>
        <win value="false"/>
    </step>
</story>

=== I-am-Gabi/BrowserChronicles/app/stories/PolyDebugNoWinningNode.xml
<?xml version="1.0"?>
<story xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="story.xsd" title="Histoire sans fin">
    <init>Story n°=0</init>
    <step id="BEGIN" type="multiChoice">
        <title>Which into the mountain</title>
        <description>After an exhausting encounter with a bugbear, four travelling heroes are grateful
            to find a small town nestled in the unfamiliar hills. Their relief quickly turns
            to suspicion, however, when they find the town of Angurkslariun uninhabited—at least by
            the living.
        </description>
        <possibility>
            <choice nextStep="s1">Go to the city.</choice>
            <choice nextStep="s3">Run, Barry, Run.</choice>
        </possibility>
    </step>
    <step id="s1" type="riddle">
        <title>Who am I?</title>
        <description>I will be yesterday, I was tomorrow.</description>
        <hint>Look at the calendar.</hint>
        <possibility>
            <choice nextStep="s2">Today</choice>
            <choice nextStep="s2">I don't know</choice>
        </possibility>
    </step>
    <step id="s2" type="memory">
        <theme>fruit</theme>
        <difficulty>2</difficulty>
        <description>Cherche les paires</description>
        <nextStep value="s3"/>
    </step>
    <step id="s3" type="multiChoice">
        <title>Seeking shelter in Angurkslariun</title>
        <description><![CDATA[
            <b>So you chose to go to the city of Angurkslariun.</b>
            The town is little more than ten or twelve buildings scattered on either side of the weedy road.
            You can see a graveyard, then an abandoned camp, then finally a cave. BUT, WAIT!
            What is that? Wraiths, possessed animals and beasts they begin to emerge from the dark places of cite.
            Then you progress further into the cave, however, you can see more human enemies... Necromancers come in
            your direction.
            <img src="https://d3b4yo2b5lbfy.cloudfront.net/wp-description/uploads/wallpapers/GW2_HumanNecromancer-1280x720.jpg" height="400"/>
        ]]></description>
        <possibility>
            <choice nextStep="BEGIN">Go to the graveyard</choice>
        </possibility>
    </step>
    <step id="s4" type="end">
        <description>Tu as perdu</description>
        <win value="false"/>
    </step>
</story>
